### ISSUE TITLE
[BUG] Windows 11 23H2 not working

### ISSUE THREAD

**Issue by Cpt-Future** [ottozumkeller/QR-Code-Reader#1]
QR-Code-Reader-1.1.0-x64.msi
Hi, 

very nice tool. 

No text is copied to the clipboard after the scan. I have tested it with several QR codes.
I have turned off the notifications for Snipping Tool.

**Comment by ottozumkeller** [comment]
I'm sorry to hear that. 
Are you getting any notifications with an error? Have you activated the clipboard history?

**Comment by Cpt-Future** [comment]
I have tested version 1.1.0 in a VM under Windows 10 (22H2) and Windows 11 (23H2). The image from the QR code is always copied to the clipboard, but not the text from the QR code. Clipboard history is deactivated. I have not received any error messages.

**Comment by ottozumkeller** [comment]
Ok, I have a few suspicions as to where the problem lies.
A few questions:
What version of Snipping Tool are you using? Make sure that Snipping Tool is up to date.
If possible, open a Powershell window with administrator rights and execute the command [Windows.Forms.Clipboard]::ContainsImage(). Ideally, True or False should be displayed. With this information i should be able to replicate your problem.

**Comment by Cpt-Future** [comment]
Version: Snipping Tool 11.2312.33.0
Command **_[Windows.Forms.Clipboard]::ContainsImage()_** does not work *

*
+ [Windows.Forms.Clipboard]::ContainsImage()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Windows.Forms.Clipboard:TypeName) [], RuntimeException
+ FullyQualifiedErrorId : TypeNotFound

**Comment by Cpt-Future** [comment]
It's a bit strange. The software seems to be working again now.
If I am too fast, it first inserts an image from the clipboard. A few moments later I get the message that the text from the QR code has been recognized.
But that's okay if you know that.
The software also works after switching the clipboard history on or off.

Since switching to Windows 11, I have also noticed that the greenshot software, for example, does not always reliably save screenshots to the clipboard. Perhaps this is also a Windows problem.

Notice: I have not tested again in the virtual machine and Windows 10!

**Comment by ottozumkeller** [comment]
I'm glad to hear that. The Windows Clipboard API is a bit unreliable. In the last version the timing was hardcoded, which probably caused a problem on slow machines. This issue should be solved now.
